/**
 * Redux action types
 */
export const FETCH_NEWS_DATA_STARTED = 'FETCH_NEWS_DATA_STARTED';
export const FETCH_NEWS_DATA_FAILED = 'FETCH_NEWS_DATA_FAILED';
export const FETCH_NEWS_DATA_COMPLETED = 'FETCH_NEWS_DATA_COMPLETED';
export const FETCH_SCORES_DATA_STARTED = 'FECTH_SCORES_DATA_STARTED';
export const FETCH_SCORES_DATA_FAILED = 'FECTH_SCORES_DATA_FAILED';
export const FETCH_SCORES_DATA_COMPLETED = 'FECTH_SCORES_DATA_COMPLETED';
export const FETCH_STANDINGS_DATA_STARTED = 'FETCH_STANDINGS_DATA_STARTED';
export const FETCH_STANDINGS_DATA_COMPLETED = 'FETCH_STANDINGS_DATA_COMPLETED';
export const FETCH_STANDINGS_DATA_FAILED = 'FETCH_STANDINGS_DATA_FAILED';
